Committing to overcome weird error message (below). The code is identical, Alex Buts thinks it is due to GIT settings on Linux and Windows for CR/LF clashing.
git.exe merge -- master
error: Your local changes to the following files would be overwritten by merge:
	_LowLevelCode/cpp/mtimesx_horace/MatMultiply.h
Please commit your changes or stash them before you merge.
Aborting
error: Your local changes to the following files would be overwritten by merge:
	_LowLevelCode/cpp/mtimesx_horace/MatMultiply.h
Please commit your changes or stash them before you merge.
Aborting
Index was not unstashed.
Merge with strategy ort failed.

git did not exit cleanly (exit code 2) (547 ms @ 02/12/2025 09:17:09)